name: FerryBan
version: ${project.version}
main: me.ferrybig.javacoding.bukkit.ferryban.Main
author: Ferrybig
description: Provides a simple ban sumpport
commands:
    pardon:
        aliases: [unban,un-ban,uban]
        permission: ferryban.pardon
        usage: /<command> <playername>
    pardon-ip:
        aliases: [unbanip,un-banip,ubanip,un-ban-ip,unban-ip,pardonip]
        permission: ferryban.pardonip
        usage: /<command> <ip-address>
    ban:
        aliases: []
        permission: ferryban.ban
        usage: /<command> <playername> [reason]
    ban-ip:
        aliases: [banip]
        permission: ferryban.banip
        usage: /<command> <ip-address> [reason]
    temp-ban:
        aliases: [tempban]
        permission: ferryban.tempban
        usage: /<command> <playername> <time> [reason]
    temp-ban-ip:
        aliases: [tempbanip,temp-banip,tempban-ip]
        permission: ferryban.tempbanip
        usage: /<command> <ip-address> <time> [reason]
    ban-info:
        aliases: [baninfo]
        permission: ferryban.baninfo
        usage: /<command> <playername>
    ban-info-ip:
        aliases: [baninfoip, ban-infoip, baninfo-ip]
        permission: ferryban.baninfoip
        usage: /<command> <ip>
    kick:
        aliases: []
        permission: ferryban.kick
        usage: /<command> <playername> [reason]
    kick-ip:
        aliases: [kickip]
        permission: ferryban.kickip
        usage: /<command> <ip-address> [reason]
    ferry-ban-reload:
        aliases: [fbr, ferrybanreload, ferryban-reload, ferry-banreload]
        permission: ferryban.reload
permissions:
    ferryban.*:
        description: All permisions for FerryBan
        default: false
        children:
            ferryban.kickip: true
            ferryban.kick: true
            ferryban.baninfo: true
            ferryban.baninfoip: true
            ferryban.tempbanip: true
            ferryban.tempban: true
            ferryban.banip: true
            ferryban.ban: true
            ferryban.pardonip: true
            ferryban.pardon: true
            ferryban.reload: true
    ferryban.kickip: 
        default: op
    ferryban.kick: 
        default: op
    ferryban.baninfo: 
        default: op
    ferryban.baninfoip: 
        default: op
    ferryban.tempbanip: 
        default: op
    ferryban.tempban: 
        default: op
    ferryban.banip: 
        default: op
    ferryban.ban: 
        default: op
    ferryban.pardonip: 
        default: op
    ferryban.pardon: 
        default: op
    ferryban.reload: 
        default: op
